import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import DirectoryContextProvider from "@/context/DirectoryContextProvider";

const monstSerrat = Montserrat()

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${monstSerrat.className} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col">
        <TRPCReactProvider>
          <DirectoryContextProvider>
            {children}
          </DirectoryContextProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
